# vim:fileencoding=utf-8:foldmethod=marker

font_family      Hack Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.0

# =============================================================================
# Theme
# =============================================================================
include                    no-preference-theme.auto.conf
background_opacity         0.9
background_blur            10


# =============================================================================
# Custom Configuration
# =============================================================================

# --- Remote Control & Listen Socket ---
allow_remote_control yes
listen_on unix:/tmp/kitty

# --- Tab Bar ---
tab_bar_style custom
tab_bar_margin_height 0 0
tab_bar_filter session:~ or session:^$
tab_title_template [{session_name}] {title}
tab_title_max_length 50

# --- Layout ---
enabled_layouts splits,stack

# --- Auto-reload config file on changes ---
config_reloading yes

# --- Session Management ---
watcher auto_save_session.py
startup_session sessions/_startup.kitty-session

# =============================================================================
# SSH Configuration
# =============================================================================
macos_option_as_alt both

# =============================================================================
# Keybindings
# =============================================================================

# --- Leader mode (ctrl+space) ---
map --new-mode leader --on-action end ctrl+space

# --- Remove annoying default keybinds ---
map cmd+enter no_op

# --- Tab management ---
map --mode leader v launch --location=vsplit --cwd=current
map --mode leader x launch --location=hsplit --cwd=current
map --mode leader r layout_action rotate
map --mode leader c close_window
map --mode leader = resize_window reset

# --- Tab movements ---

# vim-kitty-navigator
map ctrl+h neighboring_window left
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+l neighboring_window right

# Pass through to vim when focused
map --when-focus-on var:IS_VIM=true ctrl+h
map --when-focus-on var:IS_VIM=true ctrl+j
map --when-focus-on var:IS_VIM=true ctrl+k
map --when-focus-on var:IS_VIM=true ctrl+l

# --- Session management ---
map --mode leader s combine : pop_keyboard_mode : goto_session ~/.config/kitty/sessions
map --mode leader % kitten new_session.py
map --mode leader d kitten delete_session.py
map --mode leader ^ goto_session -1

# Add to current session
map cmd+t kitten new_ssh_tab.py
map cmd+shift+t kitten new_tab_in_session.py
map cmd+n new_os_window_with_cwd

# --- MISC ---

# Clear screen and scrollback
map --mode leader l combine : clear_terminal scroll active : clear_terminal scrollback active

# Fuzzy search scrollback
map --mode leader / launch --type=overlay --stdin-source=@screen_scrollback fzf --no-sort --no-mouse --exact -i

# Exit leader mode
map --mode leader esc pop_keyboard_mode
